[versions]
spigot = "1.19.3-R0.1-SNAPSHOT"

placeholder = "2.11.2"

ia = "3.2.5"

or = "-SNAPSHOT"

vault = "1.7"

[libraries]
spigot = { group = "org.spigotmc", name = "spigot", version.ref = "spigot" }

placeholder = { group = "me.clip", name = "placeholderapi", version.ref = "placeholder" }

itemsAdder = { group = "com.github.LoneDev6", name = "api-itemsadder", version.ref = "ia" }

oraxen = { group = "com.github.oraxen", name = "oraxen", version.ref = "or" }

vault = { group = "com.github.MilkBowl", name = "VaultAPI", version.ref = "vault" }

[plugins]

shadow = { id = "com.github.johnrengelman.shadow", version = "7.1.2" }